[package]
name = "solana_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
ed25519 = "2.2.3"
solana-sdk = "2.1.0"
solana-client = "2.1.0" 
tokio = { version = "1", features = ["full"] }
